"""Nakshatra-related Vedic astrology constants."""

from __future__ import annotations


# ── Nakshatras ───────────────────────────────────────────────────────────────

NAKSHATRAS = [
    "Ashwini",
    "Bharani",
    "Krittika",
    "Rohini",
    "Mrigashira",
    "Ardra",
    "Punarvasu",
    "Pushya",
    "Ashlesha",
    "Magha",
    "Purva Phalguni",
    "Uttara Phalguni",
    "Hasta",
    "Chitra",
    "Swati",
    "Vishakha",
    "Anuradha",
    "Jyeshtha",
    "Moola",
    "Purva Ashadha",
    "Uttara Ashadha",
    "Shravana",
    "Dhanishta",
    "Shatabhisha",
    "Purva Bhadrapada",
    "Uttara Bhadrapada",
    "Revati",
]

NAKSHATRAS_HI = [
    "अश्विनी",
    "भरणी",
    "कृत्तिका",
    "रोहिणी",
    "मृगशिरा",
    "आर्द्रा",
    "पुनर्वसु",
    "पुष्य",
    "अश्लेषा",
    "मघा",
    "पूर्वा फाल्गुनी",
    "उत्तरा फाल्गुनी",
    "हस्त",
    "चित्रा",
    "स्वाती",
    "विशाखा",
    "अनुराधा",
    "ज्येष्ठा",
    "मूला",
    "पूर्वाषाढ़ा",
    "उत्तराषाढ़ा",
    "श्रवण",
    "धनिष्ठा",
    "शतभिषा",
    "पूर्वा भाद्रपद",
    "उत्तरा भाद्रपद",
    "रेवती",
]

# Nakshatra lords (Vimshottari dasha sequence)
NAKSHATRA_LORDS = [
    "Ketu",
    "Venus",
    "Sun",
    "Moon",
    "Mars",
    "Rahu",
    "Jupiter",
    "Saturn",
    "Mercury",
    "Ketu",
    "Venus",
    "Sun",
    "Moon",
    "Mars",
    "Rahu",
    "Jupiter",
    "Saturn",
    "Mercury",
    "Ketu",
    "Venus",
    "Sun",
    "Moon",
    "Mars",
    "Rahu",
    "Jupiter",
    "Saturn",
    "Mercury",
]

# Nakshatra ganas: Deva, Manushya, Rakshasa
NAKSHATRA_GANAS = [
    "Deva",
    "Manushya",
    "Rakshasa",
    "Manushya",
    "Deva",
    "Manushya",
    "Deva",
    "Deva",
    "Rakshasa",
    "Rakshasa",
    "Manushya",
    "Manushya",
    "Deva",
    "Rakshasa",
    "Deva",
    "Rakshasa",
    "Deva",
    "Rakshasa",
    "Rakshasa",
    "Manushya",
    "Manushya",
    "Deva",
    "Rakshasa",
    "Rakshasa",
    "Manushya",
    "Manushya",
    "Deva",
]

# Nakshatra animals for Yoni matching (14 animal types)
NAKSHATRA_ANIMALS = [
    "Horse",
    "Elephant",
    "Goat",
    "Serpent",
    "Serpent",
    "Dog",
    "Cat",
    "Goat",
    "Cat",
    "Rat",
    "Rat",
    "Cow",
    "Buffalo",
    "Tiger",
    "Buffalo",
    "Tiger",
    "Deer",
    "Deer",
    "Dog",
    "Monkey",
    "Mongoose",
    "Monkey",
    "Lion",
    "Horse",
    "Lion",
    "Cow",
    "Elephant",
]

# Nakshatra Nadi: Aadi, Madhya, Antya
NAKSHATRA_NADIS = [
    "Aadi",
    "Aadi",
    "Aadi",
    "Madhya",
    "Madhya",
    "Madhya",
    "Antya",
    "Antya",
    "Antya",
    "Aadi",
    "Aadi",
    "Aadi",
    "Madhya",
    "Madhya",
    "Madhya",
    "Antya",
    "Antya",
    "Antya",
    "Aadi",
    "Aadi",
    "Aadi",
    "Madhya",
    "Madhya",
    "Madhya",
    "Antya",
    "Antya",
    "Antya",
]
