"""Domain models for Vedic Numerology (Anka Jyotish) analysis results.

All models use Pydantic v2 with frozen=True for immutability.
Scores use 0-100 scale; numbers use 1-9 (master numbers 11/22/33 where applicable).
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class NumberAttributes(BaseModel):
    """Lucky and astrological attributes for a single numerology number (1-9).

    Sourced from engine/knowledge/numerology_rules.yaml.
    Includes planet association, lucky items, and personality traits.
    """

    model_config = ConfigDict(frozen=True)

    number: int = Field(ge=1, le=9)
    planet: str  # Ruling planet e.g. "Sun", "Moon"
    planet_hi: str  # Hindi name e.g. "सूर्य"
    lucky_days: list[str]  # e.g. ["Sunday", "Monday"]
    lucky_colors: list[str]  # e.g. ["Gold", "Orange"]
    lucky_gemstone: str  # e.g. "Ruby"
    lucky_gemstone_hi: str  # e.g. "माणिक्य"
    lucky_direction: str  # e.g. "East"
    lucky_direction_hi: str  # e.g. "पूर्व"
    friendly_numbers: list[int]  # Numbers with harmonious vibrations
    neutral_numbers: list[int]  # Numbers with neutral compatibility
    enemy_numbers: list[int]  # Numbers with discordant vibrations
    strengths: list[str]  # Positive personality traits
    weaknesses: list[str]  # Challenging personality traits
    deity: str  # Presiding deity e.g. "Surya"
    deity_hi: str  # Hindi deity name
    mantra: str  # Beej mantra for this planet
    description: str  # Full personality description


class ArrowPattern(BaseModel):
    """A Lo Shu arrow -- three numbers forming a row, column, or diagonal.

    An arrow is 'present' when all three numbers appear at least once in the
    birth date. A 'missing' arrow occurs when none of the three are present.
    """

    model_config = ConfigDict(frozen=True)

    key: str  # Internal key e.g. "thought", "will", "action"
    name: str  # e.g. "Arrow of the Intellect"
    name_hi: str  # Hindi name
    numbers: list[int]  # The 3 numbers forming this arrow
    is_present: bool  # All 3 numbers appear in birth date
    is_missing: bool  # None of the 3 numbers appear in birth date
    plane: str  # e.g. "Mental", "Emotional", "Physical"
    plane_hi: str
    meaning: str  # What having this arrow means
    missing_meaning: str  # What missing this arrow means


class LoShuGrid(BaseModel):
    """Lo Shu 3x3 grid constructed from a birth date.

    Each cell holds the count of how many times that position's fixed number
    appears in the birth date digits (0s excluded).

    Grid layout (fixed Lo Shu arrangement):
        4  9  2
        3  5  7
        8  1  6
    """

    model_config = ConfigDict(frozen=True)

    grid: list[list[int]]  # 3x3; grid[row][col] = occurrence count
    digit_counts: dict[str, int]  # "1"-"9" → count of appearances
    present_numbers: list[int]  # Numbers appearing at least once (sorted)
    missing_numbers: list[int]  # Numbers not appearing at all (sorted)
    arrows: list[ArrowPattern]  # All 8 arrow patterns (present + absent)
    present_arrow_names: list[str]  # Names of arrows that are present
    missing_arrow_names: list[str]  # Names of arrows that are missing


class NumerologyNumbers(BaseModel):
    """The four core numerology numbers derived from birth date and name.

    Mulank and Bhagyank are always computed; Namank requires a name;
    Kua requires gender.
    """

    model_config = ConfigDict(frozen=True)

    mulank: int = Field(ge=1, le=33)  # Birth/Root number (1-9, or 11/22/33)
    mulank_compound: int | None  # Pre-reduction value when >9 (e.g. 13→4: compound=13)
    bhagyank: int = Field(ge=1, le=33)  # Destiny number
    bhagyank_compound: int | None  # Pre-reduction value when >9
    namank: int | None = Field(default=None, ge=1, le=33)  # Name number (Chaldean)
    namank_compound: int | None = None  # Pre-reduction Namank value
    kua: int | None = Field(default=None, ge=1, le=9)  # Kua / Lo Shu number
    mulank_planet: str  # Planet ruling the Mulank
    bhagyank_planet: str  # Planet ruling the Bhagyank
    namank_planet: str | None = None  # Planet ruling the Namank


class NumerologyYantra(BaseModel):
    """A 3x3 magic square (Yantra) for a given planet number.

    Each row, column, and diagonal sums to the same magic constant.
    Generated by scaling the classical Lo Shu square by the planet number.

    Base Lo Shu:
        4  9  2
        3  5  7
        8  1  6

    Magic constant = 15 x number.
    """

    model_config = ConfigDict(frozen=True)

    number: int = Field(ge=1, le=9)
    planet: str  # e.g. "Sun" for number 1
    grid: list[list[int]]  # 3x3 magic square values
    magic_constant: int  # Sum of each row / column / diagonal = 15 x number


class CompatibilityResult(BaseModel):
    """Numerology compatibility between two numbers based on planetary friendship.

    Score 0-100; category reflects the Vedic planet friendship classification.
    """

    model_config = ConfigDict(frozen=True)

    number1: int = Field(ge=1, le=9)
    number2: int = Field(ge=1, le=9)
    planet1: str
    planet2: str
    score: int = Field(ge=0, le=100)
    category: str  # "Excellent" | "Good" | "Moderate" | "Challenging"
    category_hi: str  # Hindi category label
    description: str


class NumerologyResult(BaseModel):
    """Complete Vedic Numerology analysis for a person.

    Aggregates all four core numbers, Lo Shu grid, arrow patterns,
    Yantra, and compatibility into a single result object.
    """

    model_config = ConfigDict(frozen=True)

    name: str | None  # Input name (may be None if not provided)
    dob: str  # Birth date "DD/MM/YYYY"
    gender: str | None  # "Male" or "Female" (required for Kua)
    numbers: NumerologyNumbers
    mulank_attributes: NumberAttributes  # Attributes for Mulank planet
    bhagyank_attributes: NumberAttributes  # Attributes for Bhagyank planet
    loshu_grid: LoShuGrid
    mulank_yantra: NumerologyYantra  # Yantra for Mulank number
    summary: str  # Concise human-readable overview
