"""Vedic astrology constants -- re-exports from focused sub-modules."""

from __future__ import annotations

from jyotish.domain.constants.signs import (
    SIGNS,
    SIGNS_EN,
    SIGNS_HI,
    SIGN_ELEMENTS,
    SIGN_LORDS,
    SIGN_VARNA,
    VARNA_RANK,
)
from jyotish.domain.constants.planets import (
    PLANETS,
    PLANETS_HI,
    SWE_PLANETS,
    NATURAL_FRIENDS,
    NATURAL_ENEMIES,
    NATURAL_NEUTRALS,
    COMBUSTION_LIMITS,
    COMBUSTION_LIMITS_RETROGRADE,
    SPECIAL_ASPECTS,
    DAY_PLANET,
    DAY_NAMES,
    DAY_NAMES_HI,
)
from jyotish.domain.constants.nakshatras import (
    NAKSHATRAS,
    NAKSHATRAS_HI,
    NAKSHATRA_LORDS,
    NAKSHATRA_GANAS,
    NAKSHATRA_ANIMALS,
    NAKSHATRA_NADIS,
)
from jyotish.domain.constants.dignity import (
    EXALTATION,
    EXALTATION_DEGREE,
    DEBILITATION,
    OWN_SIGNS,
    MOOLTRIKONA,
)
from jyotish.domain.constants.dashas import (
    DASHA_SEQUENCE,
    DASHA_YEARS,
    DASHA_TOTAL_YEARS,
)
from jyotish.domain.constants.houses import (
    KENDRAS,
    TRIKONAS,
    DUSTHANAS,
    UPACHAYAS,
    MARAKAS,
    TRISHADAYAS,
    AVASTHAS,
)
from jyotish.domain.constants.matching import (
    VASYA_TABLE,
    YONI_ENEMIES,
    BHAKOOT_NEGATIVE_COMBOS,
)
from jyotish.domain.constants.panchang import (
    TITHI_NAMES,
    KARANA_NAMES,
    PANCHANG_YOGA_NAMES,
    MUHURTA_FAVORABLE_NAKSHATRAS,
    RAHU_KAAL_SLOT,
    YAMAGHANDA_SLOT,
    GULIKA_SLOT,
)
from jyotish.domain.constants.astro import (
    FULL_CIRCLE_DEG,
    HALF_CIRCLE_DEG,
    DEGREES_PER_SIGN,
    NUM_NAKSHATRAS,
    MAX_NAKSHATRA_INDEX,
    NAKSHATRA_SPAN_DEG,
    PADAS_PER_NAKSHATRA,
    SARVASHTAKAVARGA_TOTAL,
    DEFAULT_CONJUNCTION_ORB,
    MAX_DAY_RATING,
    YOGINI_TOTAL_YEARS,
    ASHTOTTARI_TOTAL_YEARS,
)

__all__ = [
    # signs
    "SIGNS", "SIGNS_EN", "SIGNS_HI", "SIGN_ELEMENTS", "SIGN_LORDS",
    "SIGN_VARNA", "VARNA_RANK",
    # planets
    "PLANETS", "PLANETS_HI", "SWE_PLANETS",
    "NATURAL_FRIENDS", "NATURAL_ENEMIES", "NATURAL_NEUTRALS",
    "COMBUSTION_LIMITS", "COMBUSTION_LIMITS_RETROGRADE",
    "SPECIAL_ASPECTS", "DAY_PLANET", "DAY_NAMES", "DAY_NAMES_HI",
    # nakshatras
    "NAKSHATRAS", "NAKSHATRAS_HI", "NAKSHATRA_LORDS",
    "NAKSHATRA_GANAS", "NAKSHATRA_ANIMALS", "NAKSHATRA_NADIS",
    # dignity
    "EXALTATION", "EXALTATION_DEGREE", "DEBILITATION",
    "OWN_SIGNS", "MOOLTRIKONA",
    # dashas
    "DASHA_SEQUENCE", "DASHA_YEARS", "DASHA_TOTAL_YEARS",
    # houses
    "KENDRAS", "TRIKONAS", "DUSTHANAS", "UPACHAYAS",
    "MARAKAS", "TRISHADAYAS", "AVASTHAS",
    # matching
    "VASYA_TABLE", "YONI_ENEMIES", "BHAKOOT_NEGATIVE_COMBOS",
    # panchang
    "TITHI_NAMES", "KARANA_NAMES", "PANCHANG_YOGA_NAMES",
    "MUHURTA_FAVORABLE_NAKSHATRAS",
    "RAHU_KAAL_SLOT", "YAMAGHANDA_SLOT", "GULIKA_SLOT",
    # astro
    "FULL_CIRCLE_DEG", "HALF_CIRCLE_DEG", "DEGREES_PER_SIGN",
    "NUM_NAKSHATRAS", "MAX_NAKSHATRA_INDEX", "NAKSHATRA_SPAN_DEG",
    "PADAS_PER_NAKSHATRA", "SARVASHTAKAVARGA_TOTAL",
    "DEFAULT_CONJUNCTION_ORB", "MAX_DAY_RATING",
    "YOGINI_TOTAL_YEARS", "ASHTOTTARI_TOTAL_YEARS",
]
