"""Transit scoring tables — Gochara scores, bindu modifiers, and descriptions."""

from __future__ import annotations


# Gochara base scores per planet per house from Moon
# (from transit_rules.yaml — encoded here for runtime use)
_GOCHARA_SCORES: dict[str, dict[int, int]] = {
    "Saturn": {
        1: -1,
        2: -1,
        3: +1,
        4: -1,
        5: -1,
        6: +1,
        7: -1,
        8: -2,
        9: -1,
        10: -1,
        11: +2,
        12: -1,
    },
    "Jupiter": {
        1: -1,
        2: +1,
        3: -1,
        4: -1,
        5: +2,
        6: -1,
        7: +1,
        8: -1,
        9: +2,
        10: -1,
        11: +2,
        12: -1,
    },
    "Mars": {1: -1, 2: -1, 3: +2, 4: -1, 5: -1, 6: +2, 7: -1, 8: -2, 9: -1, 10: -1, 11: +2, 12: -1},
    "Sun": {1: -1, 2: -1, 3: +2, 4: -1, 5: -1, 6: +2, 7: -1, 8: -2, 9: -1, 10: +2, 11: +2, 12: -1},
    "Moon": {1: +1, 2: -1, 3: +1, 4: -1, 5: -1, 6: +1, 7: +2, 8: -1, 9: -1, 10: +2, 11: +2, 12: -1},
    "Mercury": {
        1: -1,
        2: +2,
        3: -1,
        4: +1,
        5: -1,
        6: +2,
        7: -1,
        8: +1,
        9: -1,
        10: +2,
        11: +2,
        12: -1,
    },
    "Venus": {
        1: +1,
        2: +2,
        3: +1,
        4: +2,
        5: +2,
        6: -1,
        7: -1,
        8: +1,
        9: +2,
        10: -1,
        11: +2,
        12: +2,
    },
    "Rahu": {1: -1, 2: -1, 3: +1, 4: -1, 5: -1, 6: +1, 7: -1, 8: -2, 9: -1, 10: +1, 11: +2, 12: -1},
    "Ketu": {1: -1, 2: -1, 3: +1, 4: -1, 5: -1, 6: +1, 7: -1, 8: -2, 9: -1, 10: +1, 11: +2, 12: +1},
}

# Ashtakavarga bindu → score modifier
_BINDU_MODIFIERS: list[tuple[range, int]] = [
    (range(0, 2), -2),  # 0-1 bindus: very unfavorable
    (range(2, 4), -1),  # 2-3 bindus: unfavorable
    (range(4, 5), 0),  # 4 bindus:   neutral
    (range(5, 7), +1),  # 5-6 bindus: favorable
    (range(7, 9), +2),  # 7-8 bindus: very favorable
]

_SCORE_LABELS: dict[int, str] = {
    -4: "Very unfavorable",
    -3: "Unfavorable",
    -2: "Unfavorable",
    -1: "Slightly unfavorable",
    0: "Neutral",
    1: "Slightly favorable",
    2: "Favorable",
    3: "Favorable",
    4: "Very favorable",
}

# Short human-readable descriptions of gochara result per planet per house from Moon
_GOCHARA_DESCRIPTIONS: dict[str, dict[int, str]] = {
    "Saturn": {
        1: "Obstacles, health issues (Sade Sati peak)",
        2: "Financial strain (Sade Sati setting)",
        3: "Success, valour",
        4: "Mental distress, property issues",
        5: "Children issues, mind disturbance",
        6: "Victory over enemies",
        7: "Travel, relationship strain",
        8: "Health crises, major losses",
        9: "Obstacles in fortune",
        10: "Career setbacks (Kantak Shani)",
        11: "Gains, prosperity",
        12: "Expenses, losses (Sade Sati rising)",
    },
    "Jupiter": {
        1: "Restlessness, loss of wealth",
        2: "Financial gains, family happiness",
        3: "Obstacles in journeys",
        4: "Property disputes",
        5: "Children's blessings, spiritual growth",
        6: "Health issues, enemy troubles",
        7: "Marriage prospects, partnerships",
        8: "Hidden troubles",
        9: "Fortune, guru blessings",
        10: "Career stagnation",
        11: "Excellent gains, aspirations fulfilled",
        12: "Expenditure, spiritual retreat",
    },
    "Mars": {
        1: "Accidents, fever, conflicts",
        2: "Financial losses, quarrels",
        3: "Courage, victory over enemies",
        4: "Property disputes, domestic conflict",
        5: "Children troubles, stomach issues",
        6: "Victory over enemies, good health",
        7: "Marital discord",
        8: "Accidents, surgeries",
        9: "Father's troubles, loss of fortune",
        10: "Career conflicts",
        11: "Gains, competitive success",
        12: "Secret enemies, expenses",
    },
    "Sun": {
        1: "Health issues, low energy",
        2: "Financial losses, family disputes",
        3: "Courage, good health",
        4: "Mental agitation",
        5: "Children troubles, loss of respect",
        6: "Victory over enemies, government favor",
        7: "Marital tension",
        8: "Health crises, fever",
        9: "Father's troubles, loss of fortune",
        10: "Career success, leadership",
        11: "Financial gains, ambitions fulfilled",
        12: "Eye problems, expenses",
    },
    "Moon": {
        1: "Good health, mental clarity",
        2: "Financial fluctuation",
        3: "Mental strength, travel success",
        4: "Mental unease",
        5: "Worries about children",
        6: "Good health, victory",
        7: "Good relationships, social ease",
        8: "Mental depression",
        9: "Obstacles in fortune",
        10: "Career success, recognition",
        11: "Financial gains, popularity",
        12: "Expenditure, fatigue",
    },
    "Mercury": {
        1: "Mental restlessness",
        2: "Financial gains, eloquent speech",
        3: "Sibling issues",
        4: "Property benefits, harmony",
        5: "Intellectual restlessness",
        6: "Victory through intellect",
        7: "Communication breakdowns",
        8: "Occult knowledge, research",
        9: "Travel delays",
        10: "Career success through communication",
        11: "Gains through intellect",
        12: "Mental confusion, expenses",
    },
    "Venus": {
        1: "Attractiveness, comfort",
        2: "Wealth gains, luxury",
        3: "Pleasant journeys, artistic success",
        4: "Domestic happiness, property gains",
        5: "Romance, children's blessings",
        6: "Relationship disputes",
        7: "Marital difficulties",
        8: "Inheritance, sensual pleasures",
        9: "Fortune, spiritual comfort",
        10: "Career not favored",
        11: "Excellent gains, luxury",
        12: "Pleasures in privacy, spiritual comfort",
    },
    "Rahu": {
        1: "Mental confusion, illusions",
        2: "Financial irregularities",
        3: "Unconventional courage",
        4: "Domestic upheaval",
        5: "Obsessive thinking, speculation",
        6: "Enemies overcome through shrewdness",
        7: "Unusual partnerships",
        8: "Hidden enemies, sudden crises",
        9: "Religious confusion",
        10: "Unconventional career success",
        11: "Material gains, large aspirations",
        12: "Hidden expenditure, fears",
    },
    "Ketu": {
        1: "Spiritual seeking, identity dissolution",
        2: "Financial losses, family detachment",
        3: "Spiritual journeys, isolation",
        4: "Domestic detachment",
        5: "Past-life karma surfacing",
        6: "Enemies subdued through karma",
        7: "Relationship detachment",
        8: "Occult experiences, transformation",
        9: "Guru detachment, dharmic questioning",
        10: "Career through spirituality",
        11: "Spiritual gains, renunciation",
        12: "Moksha inclinations, liberation",
    },
}
